"""Fix user model default values

Revision ID: b697e4ac50e3
Revises: bd484ace67eb
Create Date: 2025-03-19 16:13:17.648980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b697e4ac50e3'
down_revision = 'bd484ace67eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('upd_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upd_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
